services:
  mongodb:
    image: mongo:7.0
    container_name: node-clean-api-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  api:
    build: .
    container_name: node-clean-api-server
    restart: unless-stopped
    ports:
      - "${PORT:-5050}:${PORT:-5050}"
    env_file:
      - .env.docker
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge